export default [{
  article: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed justo sit amet ligula vulputate tincidunt vitae id ligula. Etiam luctus tincidunt malesuada. Nulla consequat vestibulum lacus a porta. Sed vulputate neque quis neque pretium euismod. Nam lacinia finibus velit, et sollicitudin urna mollis id. Morbi neque nisi, viverra laoreet rhoncus in, rutrum vel dolor. Proin nec nulla ut massa gravida molestie. Nam pulvinar elementum lacinia. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In tempus dolor mattis velit blandit, in rutrum orci ornare. Morbi euismod in lorem vel tincidunt. Morbi et dapibus nunc.',
  footNotes: ['note 1', 'note 2', 'note 3'],
  title: 'Title for 1st frame',
}, {
  article: 'The next couple of days will be important for the future of the Internet, as the European Parliament’s Committee on Legal Affairs (JURI) will vote on the proposed Copyright Directive. The Directive, which aims to update and reinforce the rights of rights holders within Europe’s Digital Market, is largely a positive step forward inasmuch as the law needs to be updated in light of modern technologies and the Internet. However, Article 13 of the directive raises serious questions about the implications for free expression, creativity, and the freedom to publish. Under this article, “information society service providers” will be required to use “content recognition technologies” to scan videos, audio, text, photos, and code to the detriment of open-source software communities, remixers, livestreamers, and meme creators.',
  footNotes: ['note 1'],
  title: 'Title for 2nd frame',
}, {
  article: 'Last week, many Internet luminaries penned an open letter to the President of the European Parliament asking for the deletion of Article 13. The Internet Society agrees with the concerns raised in this letter and urges the Parliament to reconsider Article 13 in light of the implications for the open Internet. In the meantime, civil society and academia, including EFF, EDRI, Creative Commons, and the Max Planck Institute for Innovation and Competition have all raised concerns over the potential negative impact of Article 13 on freedom of expression, the rule of law, market competition, and the Internet architecture as a whole. In their analyses, they additionally note that Article 13 is contradictory to the existing EU legislation and case law.',
  footNotes: ['note 1', 'note 2', 'note 3', 'note 4', 'note 5'],
  title: 'Title for 3rd frame',
}, {
  article: 'Firstly, Article 13 turns Internet content sharing platforms of all kinds into the “content police” obliging them to implement surveillance tools in order to carry out this function. According to cryptographer and security expert Bruce Schneier, “Aside from the harm from the provisions of Article 13, this infrastructure can be easily repurposed by government and corporations – and further entrenches ubiquitous surveillance into the fabric of the Internet. Secondly, while Article 13 calls for the introduction of, “measures, such as the use of effective content recognition technologies” (our italics), it could be argued that such technologies do not exist. As the Internet Society has written, content-blocking technology is often highly ineffective, overly broad, and even counterproductive. Technologies deployed today often block legal content and do not differentiate between fair use and copyright infringing activity.',
  footNotes: ['note 1', 'note 2'],
  title: 'Title for 4th frame',
}];
