const ACTIONS = {
  UPDATE_FRAME_INDEX: 'SNAP_SCROLL:UPDATE_FRAME_INDEX',
  FIRST_LOOK: 'SNAP_SCROLL:FIRST_LOOK',
  DISABLE: 'SNAP_SCROLL:DISABLE',
  COUNT: 'SNAP_SCROLL:COUNT',
};

export default {
  ACTIONS,
};
